services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - mynetwork

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  ngrok:
    build:
      context: .
      dockerfile: dockerfile_ngrok
    command: http https://ivandocker.com
    environment:
      - NGROK_AUTHTOKEN=2lyv2x70nWaxhdwaHS4gQ1qtvrM_fYDh11YvNChvir1Rn9R2
    ports:
      - "4040:4040"
    depends_on:
      - nginx
    networks:
      - mynetwork



volumes:
  wordpress_data:
  mysql_data:

networks:
  mynetwork:

