---
- name: install Nginx for Debian
  become: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
  notify: restart nginx

- name: install Nginx for RedHat
  become: yes
  yum:
    name: nginx
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"
  notify: restart nginx
  


- name: start Nginx Debian
  service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"

- name: start Nginx RedHat
  service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
